const express = require('express');
const multer = require('multer');
const router = express.Router();

// UPLOAD IMAGES
var storage_logos = multer.diskStorage({
    destination: function (req, file, cb) {
      cb(null, 'uploads/logos')
    },
    filename: function (req, file, cb) {
      cb(null, file.fieldname + '-' + Date.now())
    }
})
var upload_logos = multer({ storage: storage_logos })

var storage_subscription_icons = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'uploads/subscription_icons')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now())
  }
})
var upload_subscription_icons = multer({ storage: storage_subscription_icons })

var storage_products = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'uploads/products')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now())
  }
})
var upload_products = multer({ storage: storage_products })

// MIDDLEWARE
const CHECK_USER = require('../middlewares/check_user')

// ROUTES

// DASHBOARD PAGE
const DASHBOARD_PAGE = require('../company_functions/dashboard/dashboard_page')



// TRANSACTIONS
//.................................................................................................................................................................................................................................................
//..........................................................................................SSSSSSSS.....................................CCCCCC.........................................OOOOOOOO...................................SSSSSSSS........
//.TTTTTTTTTTTTTTTTTTT.RRRRRRRRRRRRRRRR............AAAAAAA........NNNNNNN.......NNNNN.....SSSSSSSSSSSS............AAAAAAA.............CCCCCCCCCCC.....TTTTTTTTTTTTTTTTTT.IIIIII.......OOOOOOOOOOOO.......NNNNNNN.......NNNNN.....SSSSSSSSSSSS......
//.TTTTTTTTTTTTTTTTTTT.RRRRRRRRRRRRRRRRR..........AAAAAAAA........NNNNNNN.......NNNNN....SSSSSSSSSSSSSS..........AAAAAAAA...........CCCCCCCCCCCCCCC...TTTTTTTTTTTTTTTTTT.IIIIII.....OOOOOOOOOOOOOOOO.....NNNNNNN.......NNNNN....SSSSSSSSSSSSSS.....
//.TTTTTTTTTTTTTTTTTTT.RRRRRRRRRRRRRRRRRR.........AAAAAAAA........NNNNNNNN......NNNNN...SSSSSSSSSSSSSSSS.........AAAAAAAA..........CCCCCCCCCCCCCCCC...TTTTTTTTTTTTTTTTTT.IIIIII.....OOOOOOOOOOOOOOOOO....NNNNNNNN......NNNNN...SSSSSSSSSSSSSSSS....
//.TTTTTTTTTTTTTTTTTTT.RRRRRRRRRRRRRRRRRRR.......AAAAAAAAAA.......NNNNNNNNN.....NNNNN...SSSSSSSSSSSSSSSSS........AAAAAAAAA.........CCCCCCCCCCCCCCCCC..TTTTTTTTTTTTTTTTTT.IIIIII....OOOOOOOOOOOOOOOOOO....NNNNNNNNN.....NNNNN...SSSSSSSSSSSSSSSSS...
//.TTTTTTTTTTTTTTTTTTT.RRRRRRRRRRRRRRRRRRR.......AAAAAAAAAA.......NNNNNNNNN.....NNNNN..SSSSSSS....SSSSSSS.......AAAAAAAAAA........CCCCCCCCC.CCCCCCCCC.TTTTTTTTTTTTTTTTTT.IIIIII...OOOOOOOO....OOOOOOOO...NNNNNNNNN.....NNNNN..SSSSSSS....SSSSSSS...
//.......TTTTTT........RRRRRR......RRRRRRR.......AAAAAAAAAA.......NNNNNNNNNN....NNNNN..SSSSSS......SSSSSS.......AAAAAAAAAAA.......CCCCCCC.....CCCCCCC.......TTTTTT.......IIIIII...OOOOOOO......OOOOOOO...NNNNNNNNNN....NNNNN..SSSSSS......SSSSSS...
//.......TTTTTT........RRRRRR.......RRRRRR......AAAAAAAAAAAA......NNNNNNNNNN....NNNNN..SSSSSS......SSSSSS.......AAAAAAAAAAA......CCCCCCC.......CCCCCC.......TTTTTT.......IIIIII...OOOOOO........OOOOOOO..NNNNNNNNNN....NNNNN..SSSSSS......SSSSSS...
//.......TTTTTT........RRRRRR.......RRRRRR......AAAAAAAAAAAA......NNNNNNNNNNN...NNNNN..SSSSSSSS................AAAAAAAAAAAA......CCCCCC........CCCCCC.......TTTTTT.......IIIIII..OOOOOOO........OOOOOOO..NNNNNNNNNNN...NNNNN..SSSSSSSS.............
//.......TTTTTT........RRRRRR......RRRRRRR......AAAAAAAAAAAA......NNNNNNNNNNN...NNNNN...SSSSSSSSSSS............AAAAAAAAAAAAA.....CCCCCC.....................TTTTTT.......IIIIII..OOOOOO..........OOOOOO..NNNNNNNNNNN...NNNNN...SSSSSSSSSSS.........
//.......TTTTTT........RRRRRRRRRRRRRRRRRR......AAAAAA..AAAAAA.....NNNNNNNNNNNN..NNNNN...SSSSSSSSSSSSSS.........AAAAAA.AAAAAA.....CCCCCC.....................TTTTTT.......IIIIII..OOOOOO..........OOOOOO..NNNNNNNNNNNN..NNNNN...SSSSSSSSSSSSSS......
//.......TTTTTT........RRRRRRRRRRRRRRRRRR......AAAAAA..AAAAAA.....NNNNNNNNNNNNN.NNNNN...SSSSSSSSSSSSSSSS......AAAAAA..AAAAAA.....CCCCCC.....................TTTTTT.......IIIIII..OOOOOO..........OOOOOO..NNNNNNNNNNNNN.NNNNN...SSSSSSSSSSSSSSSS....
//.......TTTTTT........RRRRRRRRRRRRRRRRR.......AAAAAA..AAAAAA.....NNNNNN.NNNNNN.NNNNN....SSSSSSSSSSSSSSSS.....AAAAAA..AAAAAAA....CCCCCC.....................TTTTTT.......IIIIII..OOOOOO..........OOOOOO..NNNNNN.NNNNNN.NNNNN....SSSSSSSSSSSSSSSS...
//.......TTTTTT........RRRRRRRRRRRRRRRRRR.....AAAAAA...AAAAAAA....NNNNNN..NNNNNNNNNNN......SSSSSSSSSSSSSS....AAAAAAA...AAAAAA....CCCCCC.....................TTTTTT.......IIIIII..OOOOOO..........OOOOOO..NNNNNN..NNNNNNNNNNN......SSSSSSSSSSSSSS...
//.......TTTTTT........RRRRRRRRRRRRRRRRRR.....AAAAAAAAAAAAAAAA....NNNNNN..NNNNNNNNNNN..........SSSSSSSSSSS...AAAAAAAAAAAAAAAA....CCCCCC.....................TTTTTT.......IIIIII..OOOOOO..........OOOOOO..NNNNNN..NNNNNNNNNNN..........SSSSSSSSSSS..
//.......TTTTTT........RRRRRR.....RRRRRRR.....AAAAAAAAAAAAAAAA....NNNNNN...NNNNNNNNNN..SSSSS.......SSSSSSS...AAAAAAAAAAAAAAAAA...CCCCCC........CCCCCC.......TTTTTT.......IIIIII..OOOOOOO........OOOOOOO..NNNNNN...NNNNNNNNNN..SSSSS.......SSSSSSS..
//.......TTTTTT........RRRRRR......RRRRRR....AAAAAAAAAAAAAAAAAA...NNNNNN...NNNNNNNNNN..SSSSSS.......SSSSSS..AAAAAAAAAAAAAAAAAA...CCCCCCC.......CCCCCC.......TTTTTT.......IIIIII...OOOOOO........OOOOOO...NNNNNN...NNNNNNNNNN..SSSSSS.......SSSSSS..
//.......TTTTTT........RRRRRR......RRRRRR....AAAAAAAAAAAAAAAAAA...NNNNNN....NNNNNNNNN..SSSSSS.......SSSSSS..AAAAAAAAAAAAAAAAAA...CCCCCCCC.....CCCCCCC.......TTTTTT.......IIIIII...OOOOOOO......OOOOOOO...NNNNNN....NNNNNNNNN..SSSSSS.......SSSSSS..
//.......TTTTTT........RRRRRR.......RRRRR...AAAAAAAAAAAAAAAAAAAA..NNNNNN....NNNNNNNNN..SSSSSSS.....SSSSSSS..AAAAAAAAAAAAAAAAAAA...CCCCCCCC...CCCCCCC........TTTTTT.......IIIIII...OOOOOOOO....OOOOOOOO...NNNNNN....NNNNNNNNN..SSSSSSS.....SSSSSSS..
//.......TTTTTT........RRRRRR.......RRRRR...AAAAAA.......AAAAAAA..NNNNNN.....NNNNNNNN..SSSSSSSSSSSSSSSSSS..AAAAAAA.......AAAAAA...CCCCCCCCCCCCCCCCCC........TTTTTT.......IIIIII....OOOOOOOOOOOOOOOOOO....NNNNNN.....NNNNNNNN..SSSSSSSSSSSSSSSSSS...
//.......TTTTTT........RRRRRR.......RRRRRR..AAAAAA........AAAAAA..NNNNNN......NNNNNNN...SSSSSSSSSSSSSSSSS..AAAAAA........AAAAAA....CCCCCCCCCCCCCCCC.........TTTTTT.......IIIIII.....OOOOOOOOOOOOOOOO.....NNNNNN......NNNNNNN...SSSSSSSSSSSSSSSSS...
//.......TTTTTT........RRRRRR.......RRRRRR.AAAAAAA........AAAAAAA.NNNNNN......NNNNNNN....SSSSSSSSSSSSSSS...AAAAAA........AAAAAAA....CCCCCCCCCCCCCC..........TTTTTT.......IIIIII.....OOOOOOOOOOOOOOOO.....NNNNNN......NNNNNNN....SSSSSSSSSSSSSSS....
//.......TTTTTT........RRRRRR.......RRRRRR.AAAAAA.........AAAAAAA.NNNNNN.......NNNNNN.....SSSSSSSSSSSSS...SAAAAAA.........AAAAAA.....CCCCCCCCCCCC...........TTTTTT.......IIIIII.......OOOOOOOOOOOO.......NNNNNN.......NNNNNN.....SSSSSSSSSSSSS.....
//..........................................................................................SSSSSSSSS...................................CCCCCCC.........................................OOOOOOOO...................................SSSSSSSSS.......
//.................................................................................................................................................................................................................................................

const TRANSACTION_PAGE = require('../company_functions/transactions/transaction_page')
router.get('/',CHECK_USER,TRANSACTION_PAGE.transaction_page)
router.get("/transactions",CHECK_USER,TRANSACTION_PAGE.transaction_page)


// CUSTOMERS
//..............................................................................................................................................................
//.........CCCCCC...............................................................................................................................................
//......CCCCCCCCCCC.............................................................................................................................................
//....CCCCCCCCCCCCCCC........................................ttttt..............................................................................................
//...CCCCCCCCCCCCCCCC........................................ttttt..............................................................................................
//...CCCCCCCCCCCCCCCCC.......................................ttttt..............................................................................................
//..CCCCCCCCC.CCCCCCCCC......................................ttttt..............................................................................................
//..CCCCCCC.....CCCCCCC..uuuuuu....uuuuuu.....ssssssss....ssttttttttt....ooooooooo......mmmmmmmmmmmmm..mmmmmmm........eeeeeeee......rrrrr.rrrr....ssssssss......
//.CCCCCCC.......CCCCCC..uuuuuu....uuuuuu...ssssssssssss..ssttttttttt...oooooooooooo....mmmmmmmmmmmmmmmmmmmmmmm......eeeeeeeeeee...errrrrrrrrr..ssssssssssss....
//.CCCCCC........CCCCCC..uuuuuu....uuuuuu...sssssssssssss.ssttttttttt..oooooooooooooo...mmmmmmmmmmmmmmmmmmmmmmmm....eeeeeeeeeeeee..errrrrrrrrr..sssssssssssss...
//.CCCCCC................uuuuuu....uuuuuu..ssssssssssssss.ssttttttttt.ooooooooooooooo...mmmmmmmmmmmmmmmmmmmmmmmm...eeeeeeeeeeeeee..errrrrrrrrr.rsssssssssssss...
//.CCCCCC................uuuuuu....uuuuuu..sssssss.sssssssssttttttttt.oooooooooooooooo..mmmmmmmmmmmmmmmmmmmmmmmm..meeeeeeeeeeeeee..errrrrrrrrr.rssssss.sssssss..
//.CCCCCC................uuuuuu....uuuuuu..ssssss...ssssss...ttttt...toooooo....oooooo..mmmmmm...mmmmmmm..mmmmmm..meeeee....eeeeee.errrrrrrr...rsssss...ssssss..
//.CCCCCC................uuuuuu....uuuuuu..ssssssssss........ttttt...tooooo.....oooooo..mmmmmm...mmmmmm....mmmmm..meeeee....eeeeee.errrrrr.....rsssssssss.......
//.CCCCCC................uuuuuu....uuuuuu..sssssssssssss.....ttttt...tooooo......oooooo.mmmmmm...mmmmmm....mmmmm..meeeeeeeeeeeeeee.errrrr......rssssssssssss....
//.CCCCCC................uuuuuu....uuuuuu..ssssssssssssss....ttttt...tooooo......oooooo.mmmmmm....mmmmm....mmmmm..meeeeeeeeeeeeeee.errrrr......rsssssssssssss...
//.CCCCCC........CCCCCC..uuuuuu....uuuuuu...ssssssssssssss...ttttt...tooooo......oooooo.mmmmmm....mmmmm....mmmmm..meeeeeeeeeeeeeee.errrrr.......ssssssssssssss..
//.CCCCCCC.......CCCCCC..uuuuuu....uuuuuu.....ssssssssssss...ttttt...tooooo......oooooo.mmmmmm....mmmmm....mmmmm..meeeeeeeeeeeeeee.errrrr.........ssssssssssss..
//.CCCCCCCC.....CCCCCCC..uuuuuu....uuuuuu.usssss..ssssssss...ttttt...tooooo.....oooooo..mmmmmm....mmmmm....mmmmm..meeeee.....eeeee.errrrr.....rrssss..ssssssss..
//..CCCCCCCC...CCCCCCC...uuuuuu...uuuuuuu.usssss....ssssss...ttttt....oooooo...ooooooo..mmmmmm....mmmmm....mmmmm..meeeeee...eeeeee.errrrr.....rrssss....ssssss..
//..CCCCCCCCCCCCCCCCCC...uuuuuuuuuuuuuuuu..sssssssssssssss...tttttttt.oooooooooooooooo..mmmmmm....mmmmm....mmmmm..meeeeeeeeeeeeeee.errrrr......rssssssssssssss..
//...CCCCCCCCCCCCCCCC....uuuuuuuuuuuuuuuu..sssssssssssssss...tttttttt..oooooooooooooo...mmmmmm....mmmmm....mmmmm...eeeeeeeeeeeeee..errrrr......rssssssssssssss..
//....CCCCCCCCCCCCCC......uuuuuuuuuuuuuuu..ssssssssssssss....tttttttt..oooooooooooooo...mmmmmm....mmmmm....mmmmm....eeeeeeeeeeeee..errrrr......rsssssssssssss...
//.....CCCCCCCCCCCC........uuuuuuuuuuuuuu...ssssssssssss.....tttttttt...ooooooooooo.....mmmmmm....mmmmm....mmmmm.....eeeeeeeeee....errrrr.......ssssssssssss....
//........CCCCCCC............uuuuu............ssssssss.........tttttt.....oooooooo.....................................eeeeeee....................ssssssss......
//..............................................................................................................................................................


const SUBSCRIBER_PAGE = require('../company_functions/customers/subscribers');
const MANAGE_SUBSCRIBER = require('../company_functions/customers/manage_subscriber')

router.get('/subscribers',CHECK_USER,SUBSCRIBER_PAGE.subscriber_page)
router.get('/manage_subscriber/:id',CHECK_USER,MANAGE_SUBSCRIBER.manage_subscriber)


// CATALOG
//.........................................................................................................................................................................
//................................................OOOOOOOOO...........................................................CCCCCC...............................SSSSSSSS........
//.PPPPPPPPPPPPPP......PRRRRRRRRRRRRRRR.........OOOOOOOOOOOOO.......ODDDDDDDDDDDDD.......DUUUUU.......UUUUUU.......CCCCCCCCCCC.....CCCTTTTTTTTTTTTTTTT...SSSSSSSSSSSS......
//.PPPPPPPPPPPPPPPP....PRRRRRRRRRRRRRRRR.......OOOOOOOOOOOOOOO......ODDDDDDDDDDDDDDD.....DUUUUU.......UUUUUU......CCCCCCCCCCCCCC...CCCTTTTTTTTTTTTTTTT..SSSSSSSSSSSSSS.....
//.PPPPPPPPPPPPPPPP....PRRRRRRRRRRRRRRRRR.....OOOOOOOOOOOOOOOOO.....ODDDDDDDDDDDDDDDD....DUUUUU.......UUUUUU.....CCCCCCCCCCCCCCCC..CCCTTTTTTTTTTTTTTTT.TSSSSSSSSSSSSSSS....
//.PPPPPPPPPPPPPPPPP...PRRRRRRRRRRRRRRRRR....OOOOOOOOOOOOOOOOOOO....ODDDDDDDDDDDDDDDDD...DUUUUU.......UUUUUU....CCCCCCCCCCCCCCCCC..CCCTTTTTTTTTTTTTTTT.TSSSSSSSSSSSSSSSS...
//.PPPPPPPPPPPPPPPPP...PRRRRRRRRRRRRRRRRR....OOOOOOOO...OOOOOOOO....ODDDDDDDDDDDDDDDDD...DUUUUU.......UUUUUU...UCCCCCCCC.CCCCCCCCC.CCCTTTTTTTTTTTTTTTTTTSSSSS....SSSSSSS...
//.PPPPPP.....PPPPPP...PRRRR.......RRRRRRR..ROOOOOOO......OOOOOOO...ODDDD......DDDDDDD...DUUUUU.......UUUUUU...UCCCCCC.....CCCCCCC.......TTTTTT.......TTSSSS......SSSSSS...
//.PPPPPP......PPPPPP..PRRRR........RRRRRR..ROOOOOO.......OOOOOOO...ODDDD.......DDDDDDD..DUUUUU.......UUUUUU...UCCCCC.......CCCCCC.......TTTTTT.......TTSSSS......SSSSSS...
//.PPPPPP......PPPPPP..PRRRR........RRRRRR..ROOOOO.........OOOOOO...ODDDD........DDDDDD..DUUUUU.......UUUUUU..UUCCCCC.......CCCCCC.......TTTTTT.......TTSSSSSS.............
//.PPPPPP.....PPPPPP...PRRRR.......RRRRRR...ROOOOO.........OOOOOO...ODDDD........DDDDDD..DUUUUU.......UUUUUU..UUCCCC.....................TTTTTT........TSSSSSSSSSS.........
//.PPPPPP...PPPPPPPP...PRRRRRRRRRRRRRRRRR...ROOOOO..........OOOOOO..ODDDD........DDDDDD..DUUUUU.......UUUUUU..UUCCCC.....................TTTTTT........TSSSSSSSSSSSSS......
//.PPPPPPPPPPPPPPPPP...PRRRRRRRRRRRRRRRRR...ROOOOO..........OOOOOO..ODDDD........DDDDDD..DUUUUU.......UUUUUU..UUCCCC.....................TTTTTT........TSSSSSSSSSSSSSSS....
//.PPPPPPPPPPPPPPPPP...PRRRRRRRRRRRRRRRR....ROOOO...........OOOOOO..ODDDD........DDDDDD..DUUUUU.......UUUUUU..UUCCCC.....................TTTTTT.........SSSSSSSSSSSSSSSS...
//.PPPPPPPPPPPPPPPP....PRRRRRRRRRRRRRRRR....ROOOOO..........OOOOOO..ODDDD........DDDDDD..DUUUUU.......UUUUUU..UUCCCC.....................TTTTTT...........SSSSSSSSSSSSSS...
//.PPPPPPPPPPPPPPP.....PRRRRRRRRRRRRRRRRR...ROOOOO.........OOOOOO...ODDDD........DDDDDD..DUUUUU.......UUUUUU..UUCCCC.....................TTTTTT...............SSSSSSSSSSS..
//.PPPPPPPPPPPP........PRRRR......RRRRRRR...ROOOOO.........OOOOOO...ODDDD.......DDDDDDD..DUUUUU.......UUUUUU..UUCCCCC.......CCCCCC.......TTTTTT.......TTSSS.......SSSSSSS..
//.PPPPPP..............PRRRR.......RRRRRR...ROOOOOO.......OOOOOOO...ODDDD.......DDDDDDD...UUUUUU......UUUUUU..UUCCCCC.......CCCCCC.......TTTTTT.......TTSSSS.......SSSSSS..
//.PPPPPP..............PRRRR.......RRRRRR...ROOOOOOO......OOOOOOO...ODDDD......DDDDDDD....UUUUUU.....UUUUUUU...UCCCCCC.....CCCCCCC.......TTTTTT.......TTSSSS.......SSSSSS..
//.PPPPPP..............PRRRR.......RRRRRR....OOOOOOOO...OOOOOOOO....ODDDDDDDDDDDDDDDDD....UUUUUUU...UUUUUUUU...UCCCCCCC...CCCCCCCC.......TTTTTT.......TTSSSSS.....SSSSSSS..
//.PPPPPP..............PRRRR.......RRRRRR....OOOOOOOOOOOOOOOOOOO....ODDDDDDDDDDDDDDDD.....UUUUUUUUUUUUUUUUU.....CCCCCCCCCCCCCCCCC........TTTTTT.......TTSSSSSSSSSSSSSSSS...
//.PPPPPP..............PRRRR.......RRRRRR.....OOOOOOOOOOOOOOOOO.....ODDDDDDDDDDDDDDDD.....UUUUUUUUUUUUUUUUU.....CCCCCCCCCCCCCCCC.........TTTTTT........TSSSSSSSSSSSSSSSS...
//.PPPPPP..............PRRRR.......RRRRRRR.....OOOOOOOOOOOOOOO......ODDDDDDDDDDDDDDD.......UUUUUUUUUUUUUUU.......CCCCCCCCCCCCCCC.........TTTTTT.........SSSSSSSSSSSSSSS....
//.PPPPPP..............PRRRR........RRRRRR......OOOOOOOOOOOOO.......ODDDDDDDDDDDDD..........UUUUUUUUUUUUU..........CCCCCCCCCCC...........TTTTTT..........SSSSSSSSSSSSS.....
//................................................OOOOOOOOO....................................UUUUUUUU..............CCCCCCCC..............................SSSSSSSSS.......
//.........................................................................................................................................................................
const PRODUT_PAGE = require('../company_functions/catalog/product/product_page')
const COUPONS_PAGE = require('../company_functions/catalog/coupons/coupons_page')
const SUBSCRIPTION_PLANS_PAGE = require('../company_functions/catalog/subscription_plans/subscription_plans_page')
const ADD_SUBSCRIPTION_PLAN = require('../company_functions/catalog/subscription_plans/add_subscription_plan')
const DELETE_SUBSCRIPTION_PLAN = require('../company_functions/catalog/subscription_plans/delete_subscription_plan')
const ADD_NEW_PRODUCT = require('../company_functions/catalog/product/add_new_product')
const DELETE_PRODUCT = require('../company_functions/catalog/product/delete_product')
const VIEW_PRODUCT = require("../company_functions/catalog/product/view_product")
const SELECT_SUBSCRIPTION_PLAN = require('../company_functions/catalog/product/select_subscription_plan')
const DELETE_PLAN = require('../company_functions/catalog/product/delete_plan')
const GET_PLAN_DETAILS = require('../company_functions/catalog/product/get_plan_details')
const ADD_NEW_FEATURE = require('../company_functions/catalog/product/add_new_feature')
const DELETE_FEATURE = require('../company_functions/catalog/product/delete_feature')
const ADD_NEW_COUPON = require('../company_functions/catalog/coupons/add_new_coupon')
const DELETE_COUPON = require('../company_functions/catalog/coupons/delete_coupon')
const ACTIVATE_COUPON = require('../company_functions/catalog/coupons/activate_coupon')
const DEACTIVATE_COUPON = require('../company_functions/catalog/coupons/deactivate_coupon')
const EDIT_SUBSCRIPTION_SETTING = require('../company_functions/catalog/product/edit_subscription_settings')

router.get('/products',CHECK_USER,PRODUT_PAGE.product_page)
router.get('/coupons',CHECK_USER,COUPONS_PAGE.coupons_page)
router.get('/subscription_plans',CHECK_USER,SUBSCRIPTION_PLANS_PAGE.subscription_plans_page)
router.get('/get_plan_details/:id/:no',CHECK_USER,GET_PLAN_DETAILS.get_plan_details)
router.get('/delete_subscription_plan/:id',CHECK_USER,DELETE_SUBSCRIPTION_PLAN.delete_subscription_plan)
router.get("/delete_product/:id",CHECK_USER,DELETE_PRODUCT.delete_product)
router.get('/delete_plan/:id/:no',CHECK_USER,DELETE_PLAN.delete_plan)
router.get("/view_product/:id",CHECK_USER,VIEW_PRODUCT.view_product)
router.get('/delete_coupon/:id',CHECK_USER,DELETE_COUPON.delete_coupon)
router.get('/delete_feature/:id/:id2',CHECK_USER,DELETE_FEATURE.delete_feature)
router.get('/activate_coupon/:id',CHECK_USER,ACTIVATE_COUPON.activate_coupon)
router.get('/deactivate_coupon/:id',CHECK_USER,DEACTIVATE_COUPON.deactivate_coupon)

router.post('/add_new_feature/:id',CHECK_USER,ADD_NEW_FEATURE.add_new_feature)
router.post('/add_subscription_plan',CHECK_USER,upload_subscription_icons.single("file"),ADD_SUBSCRIPTION_PLAN.add_subscription_plan)
router.post('/add_new_product',CHECK_USER,upload_products.single("file") ,ADD_NEW_PRODUCT.add_new_product)
router.post('/select_subscription_plan/:id',CHECK_USER,SELECT_SUBSCRIPTION_PLAN.select_subscription_plan)
router.post("/add_new_coupon",CHECK_USER,ADD_NEW_COUPON.add_new_coupon)
router.post('/edit_subscription_settings/:id',CHECK_USER,EDIT_SUBSCRIPTION_SETTING.edit_subscription_settings)




// BUSINESS ACCOUNTS
//.......................................................................................................................................................................................................................................................................................................................
//...............................CCCCCC................CCCCCC..............OOOOOOOOO...................................................................................SSSSSSSS......................................................................................................GGGGGGG.............SSSSSSSS........
//.........AAAAAAA.............CCCCCCCCCCC..........CCCCCCCCCCC...........OOOOOOOOOOOO.......UUUUUU.......UUUUUU...NNNNNN.......NNNNN..TTTTTTTTTTTTTTTTTT............SSSSSSSSSSSS......EEEEEEEEEEEEEEEEE.ETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.IIIIII...NNNNNN.......NNNNNN.......GGGGGGGGGGGG.........SSSSSSSSSSSS......
//........AAAAAAAA...........CCCCCCCCCCCCCC........CCCCCCCCCCCCCC.......OOOOOOOOOOOOOOOO.....UUUUUU.......UUUUUU...NNNNNNN......NNNNN..TTTTTTTTTTTTTTTTTT...........SSSSSSSSSSSSSS.....EEEEEEEEEEEEEEEEE.ETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.IIIIII...NNNNNNN......NNNNNN......GGGGGGGGGGGGGG.......SSSSSSSSSSSSSS.....
//........AAAAAAAA..........CCCCCCCCCCCCCCCC......CCCCCCCCCCCCCCCC.....OOOOOOOOOOOOOOOOO.....UUUUUU.......UUUUUU...NNNNNNN......NNNNN..TTTTTTTTTTTTTTTTTT..........SSSSSSSSSSSSSSSS....EEEEEEEEEEEEEEEEE.ETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.IIIIII...NNNNNNN......NNNNNN....GGGGGGGGGGGGGGGGG.....SSSSSSSSSSSSSSSS....
//.......AAAAAAAAAA........CCCCCCCCCCCCCCCCCC....CCCCCCCCCCCCCCCCC.....OOOOOOOOOOOOOOOOOO....UUUUUU.......UUUUUU...NNNNNNNN.....NNNNN..TTTTTTTTTTTTTTTTTT..........SSSSSSSSSSSSSSSSS...EEEEEEEEEEEEEEEEE.ETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.IIIIII...NNNNNNNN.....NNNNNN....GGGGGGGGGGGGGGGGGG....SSSSSSSSSSSSSSSSS...
//.......AAAAAAAAAA........CCCCCCCCCCCCCCCCCC...CCCCCCCCC.CCCCCCCCC...OOOOOOOO...OOOOOOOOO...UUUUUU.......UUUUUU...NNNNNNNN.....NNNNN..TTTTTTTTTTTTTTTTTT.........SSSSSSS....SSSSSSS...EEEEEEEEEEEEEEEEE.ETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.IIIIII...NNNNNNNNN....NNNNNN...GGGGGGGG....GGGGGGG...SSSSSSS....SSSSSSS...
//.......AAAAAAAAAA.......CCCCCCCC.....CCCCCCC..CCCCCCC.....CCCCCCC...OOOOOOO......OOOOOOO...UUUUUU.......UUUUUU...NNNNNNNNN....NNNNN........TTTTTT...............SSSSSS......SSSSSS...EEEEEE...................TTTTT.............TTTTTT.......IIIIII...NNNNNNNNN....NNNNNN...GGGGGGG......GGGGGGG..SSSSSS......SSSSSS...
//......AAAAAAAAAAAA......CCCCCCC......CCCCCCC..CCCCCC.......CCCCCC..OOOOOOO........OOOOOO...UUUUUU.......UUUUUU...NNNNNNNNNN...NNNNN........TTTTTT...............SSSSSS......SSSSSS...EEEEEE...................TTTTT.............TTTTTT.......IIIIII...NNNNNNNNNN...NNNNNN..GGGGGGG........GGGGGG..SSSSSS......SSSSSS...
//......AAAAAAAAAAAA......CCCCCC........CCCCCC.CCCCCCC.......CCCCCC..OOOOOO.........OOOOOOO..UUUUUU.......UUUUUU...NNNNNNNNNN...NNNNN........TTTTTT...............SSSSSSSS.............EEEEEE...................TTTTT.............TTTTTT.......IIIIII...NNNNNNNNNN...NNNNNN..GGGGGG.........GGGGGG..SSSSSSSS.............
//......AAAAAAAAAAAA......CCCCCC...............CCCCCC................OOOOOO..........OOOOOO..UUUUUU.......UUUUUU...NNNNNNNNNNN..NNNNN........TTTTTT................SSSSSSSSSSS.........EEEEEEEEEEEEEEEE.........TTTTT.............TTTTTT.......IIIIII...NNNNNNNNNNN..NNNNNN..GGGGGG..................SSSSSSSSSSS.........
//.....AAAAAA..AAAAAA.....CCCCCC...............CCCCCC................OOOOOO..........OOOOOO..UUUUUU.......UUUUUU...NNNNNNNNNNN..NNNNN........TTTTTT................SSSSSSSSSSSSSS......EEEEEEEEEEEEEEEE.........TTTTT.............TTTTTT.......IIIIII...NNNNNNNNNNN..NNNNNN..GGGGGG..................SSSSSSSSSSSSSS......
//.....AAAAAA..AAAAAA....CCCCCCC...............CCCCCC................OOOOOO..........OOOOOO..UUUUUU.......UUUUUU...NNNNN.NNNNNN.NNNNN........TTTTTT................SSSSSSSSSSSSSSSS....EEEEEEEEEEEEEEEE.........TTTTT.............TTTTTT.......IIIIII...NNNNN.NNNNNN.NNNNNN..GGGGGG.....GGGGGGGGGG...SSSSSSSSSSSSSSSS....
//.....AAAAAA..AAAAAA....CCCCCC................CCCCCC................OOOOOO..........OOOOOO..UUUUUU.......UUUUUU...NNNNN.NNNNNN.NNNNN........TTTTTT.................SSSSSSSSSSSSSSSS...EEEEEEEEEEEEEEEE.........TTTTT.............TTTTTT.......IIIIII...NNNNN..NNNNNNNNNNNN..GGGGGG.....GGGGGGGGGG....SSSSSSSSSSSSSSSS...
//....AAAAAA...AAAAAAA....CCCCCC...............CCCCCC................OOOOOO..........OOOOOO..UUUUUU.......UUUUUU...NNNNN..NNNNNNNNNNN........TTTTTT...................SSSSSSSSSSSSSS...EEEEEEEEEEEEEEEE.........TTTTT.............TTTTTT.......IIIIII...NNNNN..NNNNNNNNNNNN..GGGGGG.....GGGGGGGGGG......SSSSSSSSSSSSSS...
//....AAAAAAAAAAAAAAAA....CCCCCC...............CCCCCC................OOOOOO..........OOOOOO..UUUUUU.......UUUUUU...NNNNN..NNNNNNNNNNN........TTTTTT.......................SSSSSSSSSSS..EEEEEE...................TTTTT.............TTTTTT.......IIIIII...NNNNN...NNNNNNNNNNN..GGGGGG.....GGGGGGGGGG..........SSSSSSSSSSS..
//....AAAAAAAAAAAAAAAA....CCCCCC........CCCCCC.CCCCCCC.......CCCCCC..OOOOOO.........OOOOOOO..UUUUUU.......UUUUUU...NNNNN...NNNNNNNNNN........TTTTTT...............SSSSS.......SSSSSSS..EEEEEE...................TTTTT.............TTTTTT.......IIIIII...NNNNN...NNNNNNNNNNN..GGGGGG.....GGGGGGGGGG..SSSSS.......SSSSSSS..
//...AAAAAAAAAAAAAAAAAA...CCCCCCC.......CCCCCC.CCCCCCC.......CCCCCC..OOOOOOO........OOOOOO...UUUUUU......UUUUUU....NNNNN....NNNNNNNNN........TTTTTT...............SSSSSS.......SSSSSS..EEEEEE...................TTTTT.............TTTTTT.......IIIIII...NNNNN....NNNNNNNNNN..GGGGGGG........GGGGGG..SSSSSS.......SSSSSS..
//...AAAAAAAAAAAAAAAAAA...CCCCCCC......CCCCCC...CCCCCCC.....CCCCCCC...OOOOOOO......OOOOOOO...UUUUUUU.....UUUUUU....NNNNN....NNNNNNNNN........TTTTTT...............SSSSSS.......SSSSSS..EEEEEE...................TTTTT.............TTTTTT.......IIIIII...NNNNN....NNNNNNNNNN..GGGGGGGG......GGGGGGG..SSSSSS.......SSSSSS..
//..AAAAAAAAAAAAAAAAAAAA...CCCCCCCC..CCCCCCCC...CCCCCCCC...CCCCCCCC...OOOOOOOO...OOOOOOOOO...UUUUUUUU...UUUUUUU....NNNNN.....NNNNNNNN........TTTTTT...............SSSSSSS.....SSSSSSS..EEEEEEEEEEEEEEEEEE.......TTTTT.............TTTTTT.......IIIIII...NNNNN.....NNNNNNNNN...GGGGGGGG...GGGGGGGGG..SSSSSSS.....SSSSSSS..
//..AAAAAA.......AAAAAAA...CCCCCCCCCCCCCCCCCC....CCCCCCCCCCCCCCCCC.....OOOOOOOOOOOOOOOOOO.....UUUUUUUUUUUUUUUUU....NNNNN.....NNNNNNNN........TTTTTT...............SSSSSSSSSSSSSSSSSS...EEEEEEEEEEEEEEEEEE.......TTTTT.............TTTTTT.......IIIIII...NNNNN......NNNNNNNN....GGGGGGGGGGGGGGGGGGG..SSSSSSSSSSSSSSSSSS...
//..AAAAAA........AAAAAA....CCCCCCCCCCCCCCCC.....CCCCCCCCCCCCCCCC......OOOOOOOOOOOOOOOOO......UUUUUUUUUUUUUUUU.....NNNNN......NNNNNNN........TTTTTT................SSSSSSSSSSSSSSSSS...EEEEEEEEEEEEEEEEEE.......TTTTT.............TTTTTT.......IIIIII...NNNNN......NNNNNNNN....GGGGGGGGGGGGGGGGGGG...SSSSSSSSSSSSSSSSS...
//.AAAAAAA........AAAAAAA....CCCCCCCCCCCCCC.......CCCCCCCCCCCCCCC.......OOOOOOOOOOOOOOOO.......UUUUUUUUUUUUUUU.....NNNNN......NNNNNNN........TTTTTT.................SSSSSSSSSSSSSSS....EEEEEEEEEEEEEEEEEE.......TTTTT.............TTTTTT.......IIIIII...NNNNN.......NNNNNNN.....GGGGGGGGGGGGGGGGGG....SSSSSSSSSSSSSSS....
//.AAAAAA.........AAAAAAA.....CCCCCCCCCCCC..........CCCCCCCCCCC...........OOOOOOOOOOOO..........UUUUUUUUUUUUU......NNNNN.......NNNNNN........TTTTTT..................SSSSSSSSSSSSS.....EEEEEEEEEEEEEEEEEE.......TTTTT.............TTTTTT.......IIIIII...NNNNN.......NNNNNNN......GGGGGGGGGGGG.GGGG.....SSSSSSSSSSSSS.....
//..............................CCCCCCCC..............CCCCCCCC.............OOOOOOOOO..............UUUUUUUU.............................................................SSSSSSSSS....................................................................................................GGGGGGG..............SSSSSSSSS.......
//.......................................................................................................................................................................................................................................................................................................................

const ACCOUNT_SETTINGS_PAGE = require('../company_functions/business_account/account_settings/account_settings_page')
const UPDATE_COMPANY_PROFILE = require('../company_functions/business_account/account_settings/update_company_profile')
const UPDATE_COMPANY_LOGO = require('../company_functions/business_account/account_settings/update_company_logo')
const EMAIL_CONFIGURATION_POST  = require('../company_functions/business_account/account_settings/email_configuration_post')
const TEST_EMAIL_POST = require('../company_functions/business_account/account_settings/test_email_post')

router.get('/account_settings',CHECK_USER,ACCOUNT_SETTINGS_PAGE.account_settings_page)
router.post('/update_company_profile',CHECK_USER,UPDATE_COMPANY_PROFILE.update_company_profile)
router.post('/update_company_logo',CHECK_USER,upload_logos.single('file'),UPDATE_COMPANY_LOGO.update_company_logo)
router.post('/email_configuration',CHECK_USER,EMAIL_CONFIGURATION_POST.email_configuration_post)
router.post('/test_email',CHECK_USER,TEST_EMAIL_POST.test_email_post)

//......................................................................................................................................................................................................................................................................................................................................
//.................................................................................................................CCCCCC............................................CCCCCC..........................................................................................................................CCCCCC.............................
//.BBBBBBBBBBBBBBB............AAAAAAA.........ALLLLL..................AAAAAAA.........ANNNNN.......NNNNNN.......CCCCCCCCCCC......CEEEEEEEEEEEEEEEEE...............CCCCCCCCCCC......CUUUUU.......UUUUUU...URRRRRRRRRRRRRRR......RRRRRRRRRRRRRRRR.....REEEEEEEEEEEEEEEEE..ENNNNNN.......NNNNN.......CCCCCCCCCCC.....CCYYYYY.......YYYYYY..
//.BBBBBBBBBBBBBBBBB..........AAAAAAAA........ALLLLL..................AAAAAAAA........ANNNNNN......NNNNNN.....CCCCCCCCCCCCCCC....CEEEEEEEEEEEEEEEEE.............CCCCCCCCCCCCCCC....CUUUUU.......UUUUUU...URRRRRRRRRRRRRRRR.....RRRRRRRRRRRRRRRRR....REEEEEEEEEEEEEEEEE..ENNNNNN.......NNNNN......CCCCCCCCCCCCCC...CCYYYYY......YYYYYYY..
//.BBBBBBBBBBBBBBBBB..........AAAAAAAA........ALLLLL..................AAAAAAAA........ANNNNNN......NNNNNN....CCCCCCCCCCCCCCCC....CEEEEEEEEEEEEEEEEE............CCCCCCCCCCCCCCCC....CUUUUU.......UUUUUU...URRRRRRRRRRRRRRRRR....RRRRRRRRRRRRRRRRRR...REEEEEEEEEEEEEEEEE..ENNNNNNN......NNNNN.....CCCCCCCCCCCCCCCC...CYYYYYY.....YYYYYY...
//.BBBBBBBBBBBBBBBBBB........AAAAAAAAA........ALLLLL.................AAAAAAAAA........ANNNNNNN.....NNNNNN....CCCCCCCCCCCCCCCCC...CEEEEEEEEEEEEEEEEE............CCCCCCCCCCCCCCCCC...CUUUUU.......UUUUUU...URRRRRRRRRRRRRRRRRR...RRRRRRRRRRRRRRRRRR...REEEEEEEEEEEEEEEEE..ENNNNNNNN.....NNNNN....CCCCCCCCCCCCCCCCC...CYYYYYY....YYYYYYY...
//.BBBBBBBBBBBBBBBBBB........AAAAAAAAAA.......ALLLLL.................AAAAAAAAAA.......ANNNNNNNN....NNNNNN...CCCCCCCCC.CCCCCCCCC..CEEEEEEEEEEEEEEEEE...........CCCCCCCCC.CCCCCCCCC..CUUUUU.......UUUUUU...URRRRRRRRRRRRRRRRRR...RRRRRRRRRRRRRRRRRR...REEEEEEEEEEEEEEEEE..ENNNNNNNN.....NNNNN...NCCCCCCCC.CCCCCCCCC...YYYYYYY...YYYYYY....
//.BBBBB.......BBBBBB.......AAAAAAAAAAA.......ALLLLL................AAAAAAAAAAA.......ANNNNNNNN....NNNNNN...CCCCCCC.....CCCCCCC..CEEEEE.......................CCCCCCC.....CCCCCCC..CUUUUU.......UUUUUU...URRRRR......RRRRRRR...RRRRR.......RRRRRRR..REEEEE..............ENNNNNNNNN....NNNNN...NCCCCCC.....CCCCCCC...YYYYYYY..YYYYYYY....
//.BBBBB.......BBBBBB.......AAAAAAAAAAA.......ALLLLL................AAAAAAAAAAA.......ANNNNNNNNN...NNNNNN..NCCCCCC.......CCCCCC..CEEEEE...................... CCCCCC.......CCCCCC..CUUUUU.......UUUUUU...URRRRR.......RRRRRR...RRRRR........RRRRRR..REEEEE..............ENNNNNNNNN....NNNNN...NCCCCC.......CCCCCC....YYYYYYY.YYYYYY.....
//.BBBBB.......BBBBBB.......AAAAAAAAAAAA......ALLLLL................AAAAAAAAAAAA......ANNNNNNNNN...NNNNNN..NCCCCC........CCCCCC..CEEEEE...................... CCCCC........CCCCCC..CUUUUU.......UUUUUU...URRRRR.......RRRRRR...RRRRR........RRRRRR..REEEEE..............ENNNNNNNNNN...NNNNN..NNCCCCC.......CCCCCC.....YYYYYYYYYYYYY.....
//.BBBBBBBBBBBBBBBBBB......AAAAAA.AAAAAA......ALLLLL...............AAAAAA.AAAAAA......ANNNNNNNNNN..NNNNNN..NCCCCC................CEEEEEEEEEEEEEEEE........... CCCCC................CUUUUU.......UUUUUU...URRRRR......RRRRRRR...RRRRR.......RRRRRR...REEEEEEEEEEEEEEEE...ENNNNNNNNNN...NNNNN..NNCCCC...................YYYYYYYYYYYY......
//.BBBBBBBBBBBBBBBBB.......AAAAAA.AAAAAA......ALLLLL...............AAAAAA.AAAAAA......ANNNNNNNNNN..NNNNNN..NCCCCC................CEEEEEEEEEEEEEEEE........... CCCCC................CUUUUU.......UUUUUU...URRRRRRRRRRRRRRRRR....RRRRRRRRRRRRRRRRRR...REEEEEEEEEEEEEEEE...ENNNNNNNNNNN..NNNNN..NNCCCC....................YYYYYYYYYYY......
//.BBBBBBBBBBBBBBBBB.......AAAAAA..AAAAAA.....ALLLLL...............AAAAAA..AAAAAA.....ANNNN.NNNNNN.NNNNNN..NCCCCC................CEEEEEEEEEEEEEEEE........... CCCCC................CUUUUU.......UUUUUU...URRRRRRRRRRRRRRRRR....RRRRRRRRRRRRRRRRRR...REEEEEEEEEEEEEEEE...ENNNNNNNNNNNN.NNNNN..NNCCCC....................YYYYYYYYYY.......
//.BBBBBBBBBBBBBBBBBB.....AAAAAA...AAAAAA.....ALLLLL..............AAAAAA...AAAAAA.....ANNNN..NNNNNNNNNNNN..NCCCCC................CEEEEEEEEEEEEEEEE........... CCCCC................CUUUUU.......UUUUUU...URRRRRRRRRRRRRRRR.....RRRRRRRRRRRRRRRRR....REEEEEEEEEEEEEEEE...ENNNNN.NNNNNN.NNNNN..NNCCCC.....................YYYYYYYYY.......
//.BBBBBBBBBBBBBBBBBB.....AAAAAA...AAAAAAA....ALLLLL..............AAAAAA...AAAAAAA....ANNNN..NNNNNNNNNNNN..NCCCCC................CEEEEEEEEEEEEEEEE........... CCCCC................CUUUUU.......UUUUUU...URRRRRRRRRRRRRRRRR....RRRRRRRRRRRRRRRRR....REEEEEEEEEEEEEEEE...ENNNNN..NNNNNNNNNNN..NNCCCC.....................YYYYYYYY........
//.BBBBB.......BBBBBBB....AAAAAAAAAAAAAAAA....ALLLLL..............AAAAAAAAAAAAAAAA....ANNNN...NNNNNNNNNNN..NCCCCC................CEEEEE...................... CCCCC................CUUUUU.......UUUUUU...URRRRRRRRRRRRRRRRR....RRRRRRRRRRRRRRRRRR...REEEEE..............ENNNNN..NNNNNNNNNNN..NNCCCC......................YYYYYYY........
//.BBBBB........BBBBBB...AAAAAAAAAAAAAAAAA....ALLLLL.............AAAAAAAAAAAAAAAAA....ANNNN...NNNNNNNNNNN..NCCCCC........CCCCCC..CEEEEE...................... CCCCC........CCCCCC..CUUUUU.......UUUUUU...URRRRR.....RRRRRRR....RRRRR......RRRRRRR...REEEEE..............ENNNNN...NNNNNNNNNN..NNCCCCC.......CCCCCC........YYYYYY.........
//.BBBBB........BBBBBB...AAAAAAAAAAAAAAAAAA...ALLLLL.............AAAAAAAAAAAAAAAAAA...ANNNN....NNNNNNNNNN..NCCCCCC.......CCCCCC..CEEEEE...................... CCCCCC.......CCCCCC...UUUUUU......UUUUUU...URRRRR......RRRRRR....RRRRR.......RRRRRR...REEEEE..............ENNNNN...NNNNNNNNNN..NNCCCCC.......CCCCCC........YYYYYY.........
//.BBBBB.......BBBBBBB...AAAAAAAAAAAAAAAAAA...ALLLLL.............AAAAAAAAAAAAAAAAAA...ANNNN....NNNNNNNNNN..NCCCCCCC.....CCCCCCC..CEEEEE...................... CCCCCCC.....CCCCCCC...UUUUUU.....UUUUUUU...URRRRR......RRRRRR....RRRRR.......RRRRRR...REEEEE..............ENNNNN....NNNNNNNNN...NCCCCCC.....CCCCCCC........YYYYYY.........
//.BBBBBBBBBBBBBBBBBBB..BAAAAAAAAAAAAAAAAAA...ALLLLLLLLLLLLLLL..LAAAAAAAAAAAAAAAAAA...ANNNN.....NNNNNNNNN...CCCCCCCC...CCCCCCC...CEEEEEEEEEEEEEEEEE...........CCCCCCCC...CCCCCCC....UUUUUUU...UUUUUUUU...URRRRR.......RRRRR....RRRRR.......RRRRRR...REEEEEEEEEEEEEEEEE..ENNNNN....NNNNNNNNN...NCCCCCCC...CCCCCCCC........YYYYYY.........
//.BBBBBBBBBBBBBBBBBB...BAAAAA.......AAAAAAA..ALLLLLLLLLLLLLLL..LAAAAA.......AAAAAAA..ANNNN......NNNNNNNN...CCCCCCCCCCCCCCCCCC...CEEEEEEEEEEEEEEEEE...........CCCCCCCCCCCCCCCCCC....UUUUUUUUUUUUUUUUU....URRRRR.......RRRRR....RRRRR.......RRRRRR...REEEEEEEEEEEEEEEEE..ENNNNN.....NNNNNNNN....CCCCCCCCCCCCCCCCC.........YYYYYY.........
//.BBBBBBBBBBBBBBBBBB..BBAAAAA........AAAAAA..ALLLLLLLLLLLLLLL.LLAAAAA........AAAAAA..ANNNN......NNNNNNNN....CCCCCCCCCCCCCCCC....CEEEEEEEEEEEEEEEEE............CCCCCCCCCCCCCCCC.....UUUUUUUUUUUUUUUUU....URRRRR.......RRRRRR...RRRRR.......RRRRRR...REEEEEEEEEEEEEEEEE..ENNNNN......NNNNNNN....CCCCCCCCCCCCCCCC..........YYYYYY.........
//.BBBBBBBBBBBBBBBBB...BBAAAAA........AAAAAA..ALLLLLLLLLLLLLLL.LLAAAAA........AAAAAA..ANNNN.......NNNNNNN.....CCCCCCCCCCCCCC.....CEEEEEEEEEEEEEEEEE.............CCCCCCCCCCCCCC.......UUUUUUUUUUUUUUU.....URRRRR.......RRRRRR...RRRRR.......RRRRRRR..REEEEEEEEEEEEEEEEE..ENNNNN......NNNNNNN.....CCCCCCCCCCCCCCC..........YYYYYY.........
//.BBBBBBBBBBBBBBB.....BBAAAA.........AAAAAAA.ALLLLLLLLLLLLLLL.LLAAAA.........AAAAAAA.ANNNN.......NNNNNNN......CCCCCCCCCCCC......CEEEEEEEEEEEEEEEEE..............CCCCCCCCCCCC.........UUUUUUUUUUUUU......URRRRR.......RRRRRR...RRRRR........RRRRRR..REEEEEEEEEEEEEEEEE..ENNNNN.......NNNNNN.......CCCCCCCCCCC............YYYYYY.........
//................................................................................................................CCCCCCC...........................................CCCCCCC..............UUUUUUUU...................................................................................................CCCCCCCC............................
//......................................................................................................................................................................................................................................................................................................................................

const BALANCE_CURRENCY_PAGE = require('../company_functions/business_account/balance_currency/balance_currency_page')
const CHANGE_CURRENCY_POST = require('../company_functions/business_account/balance_currency/change_currency_post')

router.get('/balance_currency',CHECK_USER,BALANCE_CURRENCY_PAGE.balance_currency_page)
router.post('/change_currency_post',CHECK_USER,CHANGE_CURRENCY_POST.change_currency_post)


//....................................................................................................................................................................................................................................................................................................................................................
//.........................................................................................................................................................................................................................................SSSSSSSSS..............................................................GGGGGGG.............................
//.TTTTTTTTTTTTTTTTTTT.EEEEEEEEEEEEEEEEE.........AAAAAAA.........MMMMMMMM......MMMMMMMM...........MMMMMMMM......MMMMMMMM...EEEEEEEEEEEEEEEEE...MMMMMMMM......MMMMMMMM...BBBBBBBBBBBBBBBB......EEEEEEEEEEEEEEEEE...RRRRRRRRRRRRRRRR........SSSSSSSSSSSS..............PPPPPPPPPPPPPP.........AAAAAAA.............GGGGGGGGGGGG.......GGEEEEEEEEEEEEEEEE..
//.TTTTTTTTTTTTTTTTTTT.EEEEEEEEEEEEEEEEE........AAAAAAAA.........MMMMMMMM......MMMMMMMM...........MMMMMMMM......MMMMMMMM...EEEEEEEEEEEEEEEEE...MMMMMMMM......MMMMMMMM...BBBBBBBBBBBBBBBBB.....EEEEEEEEEEEEEEEEE...RRRRRRRRRRRRRRRRR.....SSSSSSSSSSSSSSS.............PPPPPPPPPPPPPPPP.......AAAAAAAA...........GGGGGGGGGGGGGGG.....GGEEEEEEEEEEEEEEEE..
//.TTTTTTTTTTTTTTTTTTT.EEEEEEEEEEEEEEEEE........AAAAAAAA.........MMMMMMMM.....MMMMMMMMM...........MMMMMMMM......MMMMMMMM...EEEEEEEEEEEEEEEEE...MMMMMMMM......MMMMMMMM...BBBBBBBBBBBBBBBBBB....EEEEEEEEEEEEEEEEE...RRRRRRRRRRRRRRRRRR....SSSSSSSSSSSSSSSS............PPPPPPPPPPPPPPPP.......AAAAAAAA..........GGGGGGGGGGGGGGGGG....GGEEEEEEEEEEEEEEEE..
//.TTTTTTTTTTTTTTTTTTT.EEEEEEEEEEEEEEEEE........AAAAAAAAA........MMMMMMMM.....MMMMMMMMM...........MMMMMMMMM....MMMMMMMMM...EEEEEEEEEEEEEEEEE...MMMMMMMMM....MMMMMMMMM...BBBBBBBBBBBBBBBBBB....EEEEEEEEEEEEEEEEE...RRRRRRRRRRRRRRRRRR...SSSSSSSSSSSSSSSSS............PPPPPPPPPPPPPPPPP.....AAAAAAAAA.........GGGGGGGGGGGGGGGGGG....GGEEEEEEEEEEEEEEEE..
//.TTTTTTTTTTTTTTTTTTT.EEEEEEEEEEEEEEEEE.......AAAAAAAAAA........MMMMMMMMM....MMMMMMMMM...........MMMMMMMMM....MMMMMMMMM...EEEEEEEEEEEEEEEEE...MMMMMMMMM....MMMMMMMMM...BBBBBBBBBBBBBBBBBB....EEEEEEEEEEEEEEEEE...RRRRRRRRRRRRRRRRRR...SSSSSSS...SSSSSSS............PPPPPPPPPPPPPPPPP.....AAAAAAAAAA........GGGGGGGG...GGGGGGGG...GGEEEEEEEEEEEEEEEE..
//.......TTTTTT........EEEEEE..................AAAAAAAAAAA.......MMMMMMMMM....MMMMMMMMM...........MMMMMMMMM....MMMMMMMMM...EEEEEE..............MMMMMMMMM....MMMMMMMMM...BBBBBB......BBBBBB....EEEEE...............RRRRR.......RRRRRRR..SSSSS......SSSSSSS...........PPPPPP.....PPPPPP....AAAAAAAAAAA.......AGGGGGG......GGGGGGG...GGEEEE..............
//.......TTTTTT........EEEEEE..................AAAAAAAAAAA.......MMMMMMMMM...MMMMMMMMMM...........MMMMMMMMM....MMMMMMMMM...EEEEEE..............MMMMMMMMM....MMMMMMMMM...BBBBBB.......BBBBB....EEEEE...............RRRRR........RRRRRR..SSSSSS......SSSSSS...........PPPPPP......PPPPPP...AAAAAAAAAAA.......AGGGGG........GGGGGG...GGEEEE..............
//.......TTTTTT........EEEEEE.................AAAAAAAAAAAA.......MMMMMMMMM...MMMMMMMMMM...........MMMMMMMMM...MMMMMMMMMM...EEEEEE..............MMMMMMMMM...MMMMMMMMMM...BBBBBB......BBBBBB....EEEEE...............RRRRR........RRRRRR..SSSSSSS......................PPPPPP......PPPPPP...AAAAAAAAAAAA......AGGGGG.........GGGGG...GGEEEE..............
//.......TTTTTT........EEEEEEEEEEEEEEEE.......AAAAAAAAAAAAA......MMMMMMMMM...MMMMMMMMMM...........MMMMMMMMMM..MMMMMMMMMM...EEEEEEEEEEEEEEEE....MMMMMMMMMM..MMMMMMMMMM...BBBBBBBBBBBBBBBBBB....EEEEEEEEEEEEEEEE....RRRRR.......RRRRRR...SSSSSSSSSSS..................PPPPPP.....PPPPPP...AAAAAA.AAAAAA.....AAGGGG..................GGEEEEEEEEEEEEEEE...
//.......TTTTTT........EEEEEEEEEEEEEEEE.......AAAAAA.AAAAAA......MMMMMMMMMM..MMMMMMMMMM...........MMMMMMMMMM..MMMMMMMMMM...EEEEEEEEEEEEEEEE....MMMMMMMMMM..MMMMMMMMMM...BBBBBBBBBBBBBBBBB.....EEEEEEEEEEEEEEEE....RRRRRRRRRRRRRRRRRR...SSSSSSSSSSSSSSS..............PPPPPP...PPPPPPPP...AAAAAA.AAAAAA.....AAGGGG..................GGEEEEEEEEEEEEEEE...
//.......TTTTTT........EEEEEEEEEEEEEEEE......AAAAAA..AAAAAA......MMMMMMMMMM.MMMMMMMMMMM...........MMMMMMMMMM..MMMMMMMMMM...EEEEEEEEEEEEEEEE....MMMMMMMMMM..MMMMMMMMMM...BBBBBBBBBBBBBBBBB.....EEEEEEEEEEEEEEEE....RRRRRRRRRRRRRRRRRR....SSSSSSSSSSSSSSS.............PPPPPPPPPPPPPPPPP...AAAAAA..AAAAAA....AAGGGG.....GGGGGGGGGG...GGEEEEEEEEEEEEEEE...
//.......TTTTTT........EEEEEEEEEEEEEEEE......AAAAAA..AAAAAAA.....MMMMMMMMMM.MMMMMMMMMMM...........MMMMM.MMMM.MMMMMMMMMMM...EEEEEEEEEEEEEEEE....MMMMM.MMMM.MMMMMMMMMMM...BBBBBBBBBBBBBBBBBB....EEEEEEEEEEEEEEEE....RRRRRRRRRRRRRRRRR......SSSSSSSSSSSSSSS............PPPPPPPPPPPPPPPPP..AAAAAA...AAAAAA....AAGGGG.....GGGGGGGGGG...GGEEEEEEEEEEEEEEE...
//.......TTTTTT........EEEEEEEEEEEEEEEE.....AAAAAAA...AAAAAA.....MMMMM.MMMM.MMMMMMMMMMM...........MMMMM.MMMMMMMMMMMMMMMM...EEEEEEEEEEEEEEEE....MMMMM.MMMMMMMMMMMMMMMM...BBBBBBBBBBBBBBBBBBB...EEEEEEEEEEEEEEEE....RRRRRRRRRRRRRRRRR........SSSSSSSSSSSSSS...........PPPPPPPPPPPPPPPP...AAAAAA...AAAAAAA...AAGGGG.....GGGGGGGGGG...GGEEEEEEEEEEEEEEE...
//.......TTTTTT........EEEEEE...............AAAAAAAAAAAAAAAA.....MMMMM.MMMMMMMMM.MMMMMM...........MMMMM.MMMMMMMMMMMMMMMM...EEEEEE..............MMMMM.MMMMMMMMMMMMMMMM...BBBBBB......BBBBBBB...EEEEE...............RRRRRRRRRRRRRRRRRR..........SSSSSSSSSSS...........PPPPPPPPPPPPPPP....AAAAAAAAAAAAAAAA...AAGGGG.....GGGGGGGGGG...GGEEEE..............
//.......TTTTTT........EEEEEE...............AAAAAAAAAAAAAAAAA....MMMMM.MMMMMMMMM.MMMMMM...........MMMMM.MMMMMMMMMMMMMMMM...EEEEEE..............MMMMM.MMMMMMMMMMMMMMMM...BBBBBB.......BBBBBB...EEEEE...............RRRRR......RRRRRRR...SSSSS......SSSSSSS...........PPPPPPPPPPPP......PAAAAAAAAAAAAAAAA....AGGGGG.....GGGGGGGGG...GGEEEE..............
//.......TTTTTT........EEEEEE..............AAAAAAAAAAAAAAAAAA....MMMMM.MMMMMMMMM.MMMMMM...........MMMMM.MMMMMMMMM.MMMMMM...EEEEEE..............MMMMM.MMMMMMMMM.MMMMMM...BBBBBB.......BBBBBB...EEEEE...............RRRRR.......RRRRRR..SSSSSS.......SSSSSS...........PPPPPP............PAAAAAAAAAAAAAAAAA...AGGGGG........GGGGGG...GGEEEE..............
//.......TTTTTT........EEEEEE..............AAAAAAAAAAAAAAAAAA....MMMMM.MMMMMMMMM.MMMMMM...........MMMMM..MMMMMMMM.MMMMMM...EEEEEE..............MMMMM..MMMMMMMM.MMMMMM...BBBBBB......BBBBBBB...EEEEE...............RRRRR.......RRRRRR..SSSSSSS......SSSSSS...........PPPPPP............PAAAAAAAAAAAAAAAAA...AGGGGGG.......GGGGGG...GGEEEE..............
//.......TTTTTT........EEEEEEEEEEEEEEEEEE..AAAAAAAAAAAAAAAAAAA...MMMMM..MMMMMMMM.MMMMMM...........MMMMM..MMMMMMMM.MMMMMM...EEEEEEEEEEEEEEEEEE..MMMMM..MMMMMMMM.MMMMMM...BBBBBBBBBBBBBBBBBBB...EEEEEEEEEEEEEEEEE...RRRRR.......RRRRRR...SSSSSSS....SSSSSSS...........PPPPPP...........PPAAAAAAAAAAAAAAAAA...AGGGGGGGG...GGGGGGGG...GGEEEEEEEEEEEEEEEE..
//.......TTTTTT........EEEEEEEEEEEEEEEEEE.AAAAAAA.......AAAAAA...MMMMM..MMMMMMM..MMMMMM...........MMMMM..MMMMMMMM.MMMMMM...EEEEEEEEEEEEEEEEEE..MMMMM..MMMMMMMM.MMMMMM...BBBBBBBBBBBBBBBBBB....EEEEEEEEEEEEEEEEE...RRRRR.......RRRRRR...SSSSSSSSSSSSSSSSSS...........PPPPPP...........PPAAAA.......AAAAAAA...GGGGGGGGGGGGGGGGGGG...GGEEEEEEEEEEEEEEEE..
//.......TTTTTT........EEEEEEEEEEEEEEEEEE.AAAAAA........AAAAAA...MMMMM..MMMMMMM..MMMMMM...........MMMMM..MMMMMMM..MMMMMM...EEEEEEEEEEEEEEEEEE..MMMMM..MMMMMMM..MMMMMM...BBBBBBBBBBBBBBBBBB....EEEEEEEEEEEEEEEEE...RRRRR.......RRRRRR....SSSSSSSSSSSSSSSS............PPPPPP..........PPPAAAA........AAAAAA....GGGGGGGGGGGGGGGGGG...GGEEEEEEEEEEEEEEEE..
//.......TTTTTT........EEEEEEEEEEEEEEEEEE.AAAAAA........AAAAAAA..MMMMM..MMMMMMM..MMMMMM...........MMMMM...MMMMMM..MMMMMM...EEEEEEEEEEEEEEEEEE..MMMMM...MMMMMM..MMMMMM...BBBBBBBBBBBBBBBBB.....EEEEEEEEEEEEEEEEE...RRRRR.......RRRRRRR...SSSSSSSSSSSSSSSS............PPPPPP..........PPPAAAA........AAAAAA.....GGGGGGGGGGGGGGGGG...GGEEEEEEEEEEEEEEEE..
//.......TTTTTT........EEEEEEEEEEEEEEEEEEEAAAAAA.........AAAAAA..MMMMM...MMMMMM..MMMMMM...........MMMMM...MMMMMM..MMMMMM...EEEEEEEEEEEEEEEEEE..MMMMM...MMMMMM..MMMMMM...BBBBBBBBBBBBBBBB......EEEEEEEEEEEEEEEEE...RRRRR........RRRRRR.....SSSSSSSSSSSS..............PPPPPP..........PPPAAA.........AAAAAAA.....GGGGGGGGGGG.GGGG...GGEEEEEEEEEEEEEEEE..
//..........................................................................................................................................................................................................................................SSSSSSSS.............................................................GGGGGGG..............................
//....................................................................................................................................................................................................................................................................................................................................................

const TEAM_MEMBER_PAGE = require('../company_functions/business_account/team_members/team_members_page')
const ADD_NEW_TEAM_MEMBER = require('../company_functions/business_account/team_members/add_new_team_member')
const GET_TEAM_MEMBER_DETAILS = require('../company_functions/business_account/team_members/get_team_member_details')
const DELETE_TEAM_MEMBER = require('../company_functions/business_account/team_members/delete_team_member')
const CHANGE_TEAM_MEMBER_ROLE = require('../company_functions/business_account/team_members/change_team_member_role')

router.get('/team_members',CHECK_USER,TEAM_MEMBER_PAGE.team_member_page)
router.get('/get_team_member_details/:id',CHECK_USER,GET_TEAM_MEMBER_DETAILS.get_team_member_details)
router.get('/delete_team_member/:id',CHECK_USER,DELETE_TEAM_MEMBER.delete_team_member)
router.post('/change_team_member_role',CHECK_USER,CHANGE_TEAM_MEMBER_ROLE.change_team_member_role)
router.post('/add_new_team_member',CHECK_USER,ADD_NEW_TEAM_MEMBER.add_new_team_member)

// DEVELOPER
//.........................................................................................................................................................................................
//..........................................................................................................OOOOOOOOO......................................................................
//.DDDDDDDDDDDDDD.......DEEEEEEEEEEEEEEEEE.EEVVVV........VVVVVV.VEEEEEEEEEEEEEEEEE..ELLLLL.................OOOOOOOOOOOO.......OPPPPPPPPPPPPP......PEEEEEEEEEEEEEEEE...ERRRRRRRRRRRRRRR.....
//.DDDDDDDDDDDDDDDD.....DEEEEEEEEEEEEEEEEE.EEVVVV.......VVVVVVV.VEEEEEEEEEEEEEEEEE..ELLLLL...............OOOOOOOOOOOOOOOO.....OPPPPPPPPPPPPPPP....PEEEEEEEEEEEEEEEE...ERRRRRRRRRRRRRRRR....
//.DDDDDDDDDDDDDDDDD....DEEEEEEEEEEEEEEEEE.EEVVVVV......VVVVVV..VEEEEEEEEEEEEEEEEE..ELLLLL..............OOOOOOOOOOOOOOOOO.....OPPPPPPPPPPPPPPPP...PEEEEEEEEEEEEEEEE...ERRRRRRRRRRRRRRRRR...
//.DDDDDDDDDDDDDDDDDD...DEEEEEEEEEEEEEEEEE..EVVVVV......VVVVVV..VEEEEEEEEEEEEEEEEE..ELLLLL..............OOOOOOOOOOOOOOOOOO....OPPPPPPPPPPPPPPPP...PEEEEEEEEEEEEEEEE...ERRRRRRRRRRRRRRRRRR..
//.DDDDDDDDDDDDDDDDDD...DEEEEEEEEEEEEEEEEE..EVVVVV......VVVVVV..VEEEEEEEEEEEEEEEEE..ELLLLL.............LOOOOOOO...OOOOOOOOO...OPPPPPPPPPPPPPPPP...PEEEEEEEEEEEEEEEE...ERRRRRRRRRRRRRRRRRR..
//.DDDDD......DDDDDDD...DEEEEE..............EVVVVVV....VVVVVV...VEEEEE..............ELLLLL.............LOOOOOO......OOOOOOO...OPPPPP.....PPPPPPP..PEEEEE..............ERRRRR......RRRRRRR..
//.DDDDD.......DDDDDDD..DEEEEE...............VVVVVV....VVVVVV...VEEEEE..............ELLLLL............LLOOOOO........OOOOOO...OPPPPP......PPPPPP..PEEEEE..............ERRRRR.......RRRRRR..
//.DDDDD........DDDDDD..DEEEEE...............VVVVVV....VVVVVV...VEEEEE..............ELLLLL............LLOOOO.........OOOOOOO..OPPPPP......PPPPPP..PEEEEE..............ERRRRR.......RRRRRR..
//.DDDDD........DDDDDD..DEEEEEEEEEEEEEEEE....VVVVVV...VVVVVV....VEEEEEEEEEEEEEEEE...ELLLLL............LLOOOO..........OOOOOO..OPPPPP.....PPPPPPP..PEEEEEEEEEEEEEEE....ERRRRR......RRRRRRR..
//.DDDDD........DDDDDD..DEEEEEEEEEEEEEEEE.....VVVVVV..VVVVVV....VEEEEEEEEEEEEEEEE...ELLLLL............LLOOOO..........OOOOOO..OPPPPP...PPPPPPPPP..PEEEEEEEEEEEEEEE....ERRRRRRRRRRRRRRRRR...
//.DDDDD........DDDDDD..DEEEEEEEEEEEEEEEE.....VVVVVV..VVVVVV....VEEEEEEEEEEEEEEEE...ELLLLL............LLOOOO..........OOOOOO..OPPPPPPPPPPPPPPPP...PEEEEEEEEEEEEEEE....ERRRRRRRRRRRRRRRRR...
//.DDDDD........DDDDDD..DEEEEEEEEEEEEEEEE.....VVVVVV..VVVVV.....VEEEEEEEEEEEEEEEE...ELLLLL............LLOOOO..........OOOOOO..OPPPPPPPPPPPPPPPP...PEEEEEEEEEEEEEEE....ERRRRRRRRRRRRRRRR....
//.DDDDD........DDDDDD..DEEEEEEEEEEEEEEEE......VVVVVVVVVVVV.....VEEEEEEEEEEEEEEEE...ELLLLL............LLOOOO..........OOOOOO..OPPPPPPPPPPPPPPP....PEEEEEEEEEEEEEEE....ERRRRRRRRRRRRRRRRR...
//.DDDDD........DDDDDD..DEEEEE.................VVVVVVVVVVVV.....VEEEEE..............ELLLLL............LLOOOO..........OOOOOO..OPPPPPPPPPPPPPP.....PEEEEE..............ERRRRRRRRRRRRRRRRR...
//.DDDDD.......DDDDDDD..DEEEEE.................VVVVVVVVVVV......VEEEEE..............ELLLLL............LLOOOO.........OOOOOOO..OPPPPPPPPPPP........PEEEEE..............ERRRRR.....RRRRRRR...
//.DDDDD.......DDDDDDD..DEEEEE..................VVVVVVVVVV......VEEEEE..............ELLLLL............LLOOOOO........OOOOOO...OPPPPP..............PEEEEE..............ERRRRR......RRRRRR...
//.DDDDD......DDDDDDD...DEEEEE..................VVVVVVVVVV......VEEEEE..............ELLLLL.............LOOOOOO......OOOOOOO...OPPPPP..............PEEEEE..............ERRRRR......RRRRRR...
//.DDDDDDDDDDDDDDDDDD...DEEEEEEEEEEEEEEEEE......VVVVVVVVV.......VEEEEEEEEEEEEEEEEE..ELLLLLLLLLLLLLLLL..LOOOOOOO...OOOOOOOOO...OPPPPP..............PEEEEEEEEEEEEEEEEE..ERRRRR.......RRRRR...
//.DDDDDDDDDDDDDDDDD....DEEEEEEEEEEEEEEEEE.......VVVVVVVV.......VEEEEEEEEEEEEEEEEE..ELLLLLLLLLLLLLLLL...OOOOOOOOOOOOOOOOOO....OPPPPP..............PEEEEEEEEEEEEEEEEE..ERRRRR.......RRRRR...
//.DDDDDDDDDDDDDDDDD....DEEEEEEEEEEEEEEEEE.......VVVVVVVV.......VEEEEEEEEEEEEEEEEE..ELLLLLLLLLLLLLLLL...OOOOOOOOOOOOOOOOO.....OPPPPP..............PEEEEEEEEEEEEEEEEE..ERRRRR.......RRRRRR..
//.DDDDDDDDDDDDDDDD.....DEEEEEEEEEEEEEEEEE.......VVVVVVV........VEEEEEEEEEEEEEEEEE..ELLLLLLLLLLLLLLLL....OOOOOOOOOOOOOOOO.....OPPPPP..............PEEEEEEEEEEEEEEEEE..ERRRRR.......RRRRRR..
//.DDDDDDDDDDDDDD.......DEEEEEEEEEEEEEEEEE........VVVVVV........VEEEEEEEEEEEEEEEEE..ELLLLLLLLLLLLLLLL......OOOOOOOOOOOO.......OPPPPP..............PEEEEEEEEEEEEEEEEE..ERRRRR.......RRRRRR..
//..........................................................................................................OOOOOOOOO......................................................................
//.........................................................................................................................................................................................
const ALERT_WEBHOOKS = require('../company_functions/alerts_webhooks/alerts_webhooks')
const ALERT_WEBHOOKS_POST = require('../company_functions/alerts_webhooks/alert_webhooks_post')


router.get('/alerts_webhooks',CHECK_USER,ALERT_WEBHOOKS.alerts_webhooks)
router.post('/alert_webhooks_post',CHECK_USER,ALERT_WEBHOOKS_POST.alert_webhooks_post)

module.exports = router;